### ISSUE TITLE
ERXFileUtilities.pathForResourceNamed 'Can't get path when run as jar'

### ISSUE THREAD

**Issue by sal-bock** [wocommunity/wonder#1003]
this is nasty in dev mode  when the application tries to get resources  from a true-jar framework (located in ~/.m2/repository/..)

in  2004 Anjo  may have had some reason to implement the method this way but nowadays  WO 5.4 is able to provide the requested information ;-)

**Comment by lbane** [comment]
I'm not sure about this. I think `pathForResourceNamed` must return a real filesystem path, and this does not work with URL like paths needed to locate files inside Jars.
For example `ERXFileUtilities.pathForResourceNamed("Localizable.strings", "ERExtensions", NSArray.of("English"))` may return something like `file:///Users/auser/.m2/repository/wonder/core/ERExtensions/7.4.3/ERExtensions-7.4.3.jar!/Resources/English.lproj/Localizable.strings` when the jar check is disabled. But this string is missing the `jar:` prefix that the real URL has, and is unusable for locating anything.

The URL version `pathURLForResourceNamed` should be used instead where appropriate. There are a few places, especially when locating property files, that currently still use `pathForResourceNamed` where the URL version might be better suited.

**Comment by sal-bock** [comment]
Well, both `pathURLForResourceNamed` and `pathForResourceNamed` will call `application.resourceManager.pathURLForResourceNamed`.  So in a normal scenario they will return the same result. In addition, `pathForResourceNamed` will check if application is null and tries to look for the corresponding NSBunde to retrieve the pathURL.

Is there (still) a use case, where `WOApplication.application()` will return `null`?  If not, we could mark `pathForResourceNamed` as deprecated (or redundant).

**Comment by sal-bock** [comment]
It turns out, that ERXProperties fails to read the Properties during application startup (via EXProperties.applyConfiguration). But this is another issue. But at the end, all expected properties are loaded somehow.

**Comment by sal-bock** [comment]
> I'm not sure about this. I think `pathForResourceNamed` must return a real filesystem path, and this does not work with URL like paths needed to locate files inside Jars. [...]

 I finally see that there is subtile difference between url.getFile() and url.toExternalForm().  

> The URL version `pathURLForResourceNamed` should be used instead where appropriate. There are a few places, especially when locating property files, that currently still use `pathForResourceNamed` where the URL version might be better suited.

Ok, I will fix ERXNavigationManager.registerObserverForFramework, which will throw an NullPointerException, if the navigationMenuFile is contained in a jar.
