### ISSUE TITLE
ERXNavigationManager.registerObserverForFramework  throws an NullPointerException

### ISSUE THREAD

**Issue by sal-bock** [wocommunity/wonder#1005]
ERXNavigationManager.registerObserverForFramework  throws an NullPointerException, if the navigationMenuFile is contained in a jar.

the reason is, that ERXFileUtilities.pathForResourceNamed returns null, when the navigationMenuFile is contained in a jar.

Using pathURLForResourceNamed should fix the problem.

**Comment by paulhoadley** [comment]
I assume this was fixed in #1006.
