### ISSUE TITLE
hard coded DriverClassName in MySQLPlugin

### ISSUE THREAD

**Issue by sal-bock** [wocommunity/wonder#1009]
The class name of the mysql java connector has been changed with version 8.0.x

Launching an Application with mysql-connector-java Version 8.0.28 leads to the following exception:

`Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
`

When using the mariadb-java-client (version 3.1.2), the application will not start, because the class 'com.mysql.jdbc.Driver' is not found.

A quick fix would be to assign null or blank to the constant 'com.webobjects.jdbcadaptor._MySQLPlugIn.DriverClassName

**Comment by paulhoadley** [comment]
PR merged—thanks.
