### ISSUE TITLE
ERXFormat based on headers

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#13]
ERXRouteController.format() should check the Accept and Content-Type header to figure out the format to use if it was not specified in the URL. For example, JBoss' RestEasy client use Content-Type (bad idea, it should be Accept, but anyway) to specify the preferred format.

**Comment by paulhoadley** [comment]
Closing as an ancient ticket: if someone wants to adopt this idea, by all means re-open this ticket.
