### ISSUE TITLE
WOAdaptor receive timeout setting from within Eclipse

### ISSUE THREAD

**Issue by darkv** [wocommunity/wonder#134]
You can start an instance from within Eclipse and run through Apache instead of using DirectConnect. The problem is that the adaptor has a receive timeout of 30 seconds so if you have a breakpoint in code the adaptor will quickly timeout and display a **No instance available** error.
It should be checked if it is possible to set the timeout interval to a greater number automatically when starting the instance in Eclipse to prevent this situation.

**Comment by paulhoadley** [comment]
Hey @darkv, is this something you're still interested in doing?

**Comment by darkv** [comment]
I may be looking into this some day if time permits. Until then we can close it.
