### ISSUE TITLE
multiple relationships to one entity on one page with ERModern does not work

### ISSUE THREAD

**Issue by johanhenselmans** [wocommunity/wonder#140]
If you have multiple relationships to one entitity on one page in ERModern, this will not work because there will be multiple identical id's. 

Suppose you hava A.r1->B and A.r2->B, than you can not change the second page in a Create or and Edit page, because the id's of the component that is supposed to take care of that are similar. 

A solution would be to create a name that would not only contain the name of the entities, but also the name of the relations, as these are supposed to have different names. So: ERMDRelationshipB would be ERMDRelationShopr1B, or in mycase:
MUC_EditRelationshipEmbeddedContact would become: MUC_EditRelationshipEmbeddedPubliciteitContact, and MUC_EditRelationshipEmbeddedTechniekContact

Does that make sense?

**Comment by fbarthez** [comment]
This was fixed in [44c03bd].
