### ISSUE TITLE
Unit tests for ERRest

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#241]
ERRest should have the following unit tests:
- CRUD actions on a EO 
  - Create should expect a 201 status code, all others a 200 status code
  - PUT/POST with missing attributes should send a 400 Bad Request
  - Check the Content-Type header from the response to see if it's valid
  - Parse the value from the response to see if it's the correct format
- CRUD actions on a POJO
  - Same as EO
- Send a NSDictionary in a response
  - Also send a empty dictionary
- Send a NSArray of primitives in a response
  - Also send a empty array
- Compound primary keys
- Sending a NSDictionary in a EO, to make sure the content of the dict is there
- Tests with major client-side JS frameworks (Montage, Dojo, jQuery, etc.)

**Comment by paulhoadley** [comment]
Closing this as stale—great ideas, but obviously needs someone to adopt the issue and do the work.
