### ISSUE TITLE
Javadoc languages

### ISSUE THREAD

**Issue by maiksd** [wocommunity/wonder#295]
I'm wondering if we should restrict Wonder javadoc to english only. I'm getting more and more japanese filling my view in javadoc popup windows and stuff, which is slowing me down. Think it through: if everybody would provide javadoc in his native and/or well-known foreign languages, what a mess that would be.

And there is a serious problem with documentation that only a fraction of the community understands: if someone else changes the code, there is no way for him to check if the foreign-language javadoc is still valid or has become wrong.

So I propose as a guideline: english javadoc and source code comments only in Wonder, and get rid of everything else.

Comments?

**Comment by paulhoadley** [comment]
Closing this as stale—let's just leave the documentation as is for now.
