### ISSUE TITLE
password encryption mismatch

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#325]
It seems that the encryption code in wotaskd (to be exact, in MSiteConfig.encryptStringWithKey) is not generating the same key. It's problematic if you have two wotaskd installations with the same password, because the encryption key might not be the same and if you have one JavaMonitor to manage both installations, you won't be able to manage the wotaskd installations.

**Comment by paulhoadley** [comment]
Closing as stale—we'd need to know how to reproduce the issue.
