### ISSUE TITLE
ERXEC and serialization

### ISSUE THREAD

**Issue by soidisant** [wocommunity/wonder#387]
field  NSMutableDictionary<Thread, NSMutableArray<Exception>> openLockTraces of er.extensions.eof.ERXEC should be made transient 

if er.extensions.ERXEC.traceOpenLocks=true or er.extensions.ERXEC.markOpenLocks=true
and openLockTraces is not transient then the serialization fails.

**Comment by paulhoadley** [comment]
This sounds like a reasonable workaround. Given the age of this issue, I'm closing it.
