### ISSUE TITLE
ERXHttpStatusCodes.STATUS_FORBIDDEN typo

### ISSUE THREAD

**Issue by paulhoadley** [wocommunity/wonder#676]
`ERXHttpStatusCodes.STATUS_FORBIDDEN` should probably be renamed to `ERXHttpStatusCodes.FORBIDDEN` for consistency: none of the other labels have that `STATUS_` prefix, and the label from the spec is just "Forbidden".

We could do this while we're making other backwards-incompatible changes for Wonder 7.

**Comment by darkv** [comment]
Has been merged into master.

**Comment by gavineadie** [comment]
The `STATUS_FORBIDDEN` change to `FORBIDDEN` also needs to be made in two other places where the former is used.  If I was clever, I'd submit a pull request, but I'm sure someone can cope with knowing the two files are:

    Applications/JavaMonitor/Sources/com/webobjects/monitor/application/AdminAction.java
    Frameworks/Core/ERExtensions/Sources/er/extensions/appserver/ERXDirectAction.java

on the Wonder_7 branch.

**Comment by darkv** [comment]
Hi Gavin, those two classes have been changed already in the master branch (see commit 6e2cdf5). The former Wonder_7 branch has been removed as master represents the current Wonder7 development. Be sure to update your sources accordingly.

**Comment by gavineadie** [comment]
.. oops, I hadn't appreciated that `master` represents the current Wonder7 development.  I come back to this project quite infrequently; apologies for the noise, but a good New Year to all while I'm here ..
