### ISSUE TITLE
JavaMonitor bounce = no instance available

### ISSUE THREAD

**Issue by algodata44** [wocommunity/wonder#716]
Bonjour,

J'ai un problème lors du Bounce de mon application sur JavaMonitor. Mon application a 10 instances de lancées et 17 de configurées.

Pour mettre en production ma nouvelle version de mon application :
- Je vais dans les configurations générales de l'application et je change le 'path'
- je vais dans le 'details view' et je clique sur le lien 'Bounce'

Tout se passe bien, les 10 instances se mettent en 'Refuse new sessions' à ON et une 11e instance a été  lancée.

Le problème : tant que je n'ai pas 1 des 10 instances qui se termine normalement et se relance, j'ai par intermittence des 'no instance available'.

Savez-vous d'où vient le problème? Cela fait des années que j'essaie plusieurs solution mais rien ne fonctionne.

Merci d'avance.

**Comment by renebock** [comment]
Aucun message error?

Mais je crois, qu' au lieux de changer le 'path' , c'est mieux de 'bouger' l'application.  Par exemple:

cd  ~/upload
tar xvz MyApp.woa.tgz
mv /Library/WebObjects/Application/MyApp.woa  ~/woarchive
mv ~/upload/MyApp.woa /Library/WebObjects/Application

wget http://monitorhost:56789/cgi-bin/WebObjects/JavaMonitor.woa/admin/bounce?type=app&name=MyApp

(voir https://wiki.wocommunity.org/display/documentation/Wonder+JavaMonitor+and+wotaskd#WonderJavaMonitorandwotaskd-RemoteControlviaRESTRoutes%28forJavaMonitor%29)

Regrards,

  René

**Comment by algodata44** [comment]
Non aucun message d'erreur.
J'essaierai sans le changement du path pour voir.
Mais je sais que nous n'avions pas ce problème auparavant. Est-ce cela pourrait provenir du mode "URL rewrite rules"?

Merci pour la réponse en tous cas.

**Comment by chillatgvc** [comment]
Bonjour,

My apologies but my written French is even worse than my spoken French.  Pascal can verify.  :-)

What you are seeing is a symptom of a thread not stopping when the application is told to terminate.  This usually has one of two causes:
1. A WOWorkerThread got stuck or deadlocked
2. Your application created and started a Thread but did not call thread.setDaemon(true), or provide for a way for the thread to stop when the application is told to terminate.

To help diagnose this, go into JavaMonitor and mark one instance as ‘Refuse new sessions’.  Wait a couple of minutes and if it does not restart, then determine the process id and get a thread dump with this command:

sudo jstack –F <process id> > stuckinstance.log

Put the stuckinstance.log here and one of us can help to diagnose the exact problem.

Chuck

**Comment by algodata44** [comment]
Bonjour,

Mes instances redémarrent correctement lorsque je mets 'Refuse new sessions'. Le mode Scheduler est configuré sur mon application et toutes mes instances redémarrent correctement tous les jours.
C'est rare qu'une instance reste bloqués à cause d'un thread non stoppé.
Par contre, est-ce que cela signifie que tous les Threads en WebObjects doivent être en setDaemon(true)?

**Comment by algodata44** [comment]
Voici le fichier de log
[stuckinstance.txt](https://github.com/wocommunity/wonder/files/62441/stuckinstance.txt)

**Comment by chillatgvc** [comment]
Bonjour,

All threads in WebObjects must do one of two things:
1) Have setDaemon(true)
2) Be stopped when terminate() is called on the application
WOWorkerThreads are an example of (2).  If a thread is not set to be a daemon thread and is not stopped when terminate() is called on the application, then the JVM will not stop.  If the JVM does not stop, the instance cannot restart.

The log you sent appears normal to me.  The WOWorkerThreads are all running.  That probably means that the instance had restarted before you run the jstack command.  You will need to wait until you get an instance that is not restarting.

**Comment by algodata44** [comment]
Bonjour,

Le problème ne vient pas d'instance qui ne redémarre pas mais du fait que quand je clique sur "Bounce" j'ai des "no instance available" tant qu'une instance sur une ancienne version de l'app redémarre.
A partir du moment où une instance sur l'ancienne version de l'app redémarre, je n'ai plus de "no instance available".

**Comment by algodata44** [comment]
Bonjour,
Voici un nouveau fichier avec une instance bloquée :
[stuckinstance.txt](https://github.com/wocommunity/wonder/files/73072/stuckinstance.txt)

**Comment by chillatgvc** [comment]
Bonjour,

I don't see anything blocked there.  It looks like an idle application (there are WOWorkerThreads, but zero requests being processed).

**Comment by paulhoadley** [comment]
Hi,

I'm going to close this issue if there's nothing further here.
