### ISSUE TITLE
CookieParser: Found a null cookie value in:...Will continue by setting value to the empty string

### ISSUE THREAD

**Issue by algodata44** [wocommunity/wonder#772]
Bonjour,

J'obtiens des erreurs de CookieParser sur des instances qui ont le "refuse new sessions" à TRUE :
CookieParser: Found a null cookie value in: '...'. Will continue by setting value to the empty string

J'ai également des erreurs de ce type : NSLog  - <WOApplication> !!! _initializeSessionInContext: called with refuseNewSessions set !!!

Comment est-ce possible? Le loadBalancing ne fonctionne pas ou mal?

Merci d'avance pour les réponses.

**Comment by paulhoadley** [comment]
Google translate:

> Hello,
> 
> I am getting CookieParser errors on instances that have the "refuse new sessions" set to TRUE:
CookieParser: Found a null cookie value in: '...'. Will continue by setting value to the empty string

I don't know what to make of this.

> I also have errors like this: NSLog - !!! _initializeSessionInContext: called with refuseNewSessions set !!!
> 
> How is it possible? The loadBalancing does not work or does not work well?

This can happen if someone has a bookmark or a cookie with the instance number in it. Chuck Hill provided [a solution on the mailing list](https://lists.apple.com/archives/webobjects-dev/2015/May/msg00157.html) back in 2015.
