### ISSUE TITLE
Possible memory leak in ERXStatisticsStore/StopWatchTimer

### ISSUE THREAD

**Issue by NochEinKamel** [wocommunity/wonder#811]
Hi everyone,

we've encountered an odd issue where the HashMaps in the StopWatchTimer would take up large amounts of Memory (40% of Heap).

We've looked into the StopWatchTimer class and found this behaviour for long running requests:

In checkThreads() the duration of each active request is measured.
If the duration exceeds a certain warning duration the Thread dumps of ALL active threads are stored in the _warnTraces and _warnTracesNames HashMaps.
If the duration also exceeds a certain error duration the Thread dumps of ALL active threads are stored in the _errorTraces and _errorTracesNames HashMaps.
And if the duration also exceeds a certain fatal duration the Thread dumps of ALL active threads are stored in the _fatalTraces and _fatalTracesNames HashMaps.

That means for a request taking 61 seconds and the warning, error and fatal level set to e.g. 15, 30 and 60 seconds there will be SIX dictionarys with information of all running threads.

Now, when the thread is finally done the endTimer method is called which checks the duration again and provides the corresponding output.
However the way the traces are obtained from the above mentioned HashMaps it will only take into account the most severe trace available and only that trace will be removed from the HashMaps.
In the 61 seconds request the information stored in the _warn* and _error* HashMaps still exist after the endTimer method is done.

And as we have a system under distress with 300+ threads the HashMaps become really big

This obviously is only a problem if requests start taking a long time in the first place (i.e. longer than _maximumRequestErrorTime/2).
Also an easy workaround is to "disable" the warning and error HashMaps by setting the threshold to unrealistic values (e.g. over 9000) if you don't want to disable the StatisticsStore completely and want to keep the fatal-warning level.

----

We initially thought that it wouldn't matter because WeakHashMaps were used and GC would just clean up, but as the keys are worker threads which are beeing reused the HashMaps probably won't ever be cleaned up by GC (or at least not before the WorkerThreadPool decides to kill a worker thread if he ever does that).

**Comment by ishimoto** [comment]
You are correct, thanks. Have fixed that in our Solution.

**Comment by renebock** [comment]
Hi Ken, 
is there any chance that you share your fixes?

**Comment by darkv** [comment]
see #820
