### ISSUE TITLE
ERComponentTour example Captcha doesn't work

### ISSUE THREAD

**Issue by witchi** [wocommunity/wonder#835]
I'll get an exception, if I go to the Captcha page in the example.

`Sep 23 14:13:45 ERComponentTour[38426] ERROR er.captcha.ERCaptcha  - Failed to create JPEG for Captcha.
NoClassDefFoundError: Could not initialize class com.octo.captcha.image.gimpy.GimpyFactory
  at er.captcha.ERCaptchaEngine.buildInitialFactories(ERCaptchaEngine.java:58)
  at com.octo.captcha.engine.image.ListImageCaptchaEngine.<init>(ListImageCaptchaEngine.java:24)
  at er.captcha.ERCaptchaEngine.<init>(ERCaptchaEngine.java:35)`

First I thought, it depends on a security setting of ImageMagick. I have added some policies, which I found on the net to /etc/ImageMagick/policy.xml:

`<policy domain="path" rights="none" pattern="@*" />
  <policy domain="coder" rights="read | write" pattern="JPEG" />
  <policy domain="coder" rights="read | write" pattern="PNG" />`

But these policies did not change something.
Any ideas?

**Comment by witchi** [comment]
Seems to come from jcaptcha framework, it uses com.sun.image.codec.jpeg.ImageFormatException, but this class has been deprecated/removed since Java 1.4?

**Comment by paulhoadley** [comment]
Hi André,

You could easily be the first person to even _look_ at this code in _years_. I think your options are limited to fixing it yourself. If you open a pull request, I can review and merge it.

**Comment by paulhoadley** [comment]
I can't reproduce the exception above, but I can confirm that CaptchaPage generates no usable image. Short of someone adopting `ERCaptcha.framework`, this will never be fixed.
