### ISSUE TITLE
WONDER-713 Derby plugin creates wrong sql

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#88]
Reported by Greg Brown

When Entity modeler creates sql for an index, the statement is like: create index indname >>> FOR<<<< tablename(col). But Derby says: 

CREATE [UNIQUE] INDEX index-Name >>>ON<<< table-Name ( Simple-column-Name [ ASC | DESC ] 
[ , Simple-column-Name [ ASC | DESC ]] \* ) 

For vs On, one works one doesn't

**Comment by witchi** [comment]
Seems to be solved, the ERXSQLHelper class contains "ON" already.

**Comment by paulhoadley** [comment]
Unless a Derby user wants to adopt this ticket, I suggest we take @witchi's word for it and close this as fixed.
