### ISSUE TITLE
Pull request is not visible

### ISSUE THREAD

**Issue by markusstoll** [wocommunity/wonder#881]
I created a pull request

Fix deadlock in WOAdaptor #880

which is not visible / accessible. When I try to recreate it, I get errors with "pull request already created". So I am somehow stuck with this….

**Comment by hugith** [comment]
GitHub is partially down at the moment.

https://status.github.com/messages <https://status.github.com/messages>

- hugi

**Comment by markusstoll** [comment]
was indeed a github problem, fixed by now
