### ISSUE TITLE
wotaskd won't start

### ISSUE THREAD

**Issue by algodata44** [wocommunity/wonder#884]
Hi,

After installation wonder (following the wiki instruction), wotaskd won't start.

The error message :

/System/Library/Frameworks/JavaXML.framework/Resources/Java/javaxml.jar
java.lang.NoClassDefFoundError: er/extensions/appserver/ERXApplication

I can't find why...

**Comment by paulhoadley** [comment]
Hi,

Did you end up sorting this out? I think it's going to be hard to diagnose and help with this issue in this forum. If you still need help, subscribe to the [WebObjects Development list](https://lists.apple.com/mailman/listinfo/webobjects-dev) and ask there.
