### ISSUE TITLE
Wrong errors when a specific request is missing

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#9]
When a non-Apple provided request handler is not registered, for example ERXRouteRequestHandler, if you try to get an URL that use that handler, we get an "Session has timeout" error page instead of a more useful error (or a 404). I don't know if it's possible to change this behavior, but if it is, we should change it.

**Comment by paulhoadley** [comment]
Closing as an ancient ticket: if someone wants to adopt this idea, by all means re-open this ticket.
