### ISSUE TITLE
AjaxAutocomplete doesn't render in correct place if window scrolled, since prototype 1.7.3

### ISSUE THREAD

**Issue by timcu** [wocommunity/wonder#905]
If I have scrolled the window before entering text in an AjaxAutocomplete, the drop-down menu will be rendered at a position which is offset from the correct position by the amount scrolled. This behaviour did not occur with prototype 1.7.2 but does occur with prototype 1.7.3. It is repeatable. Even the sample AjaxAutocomplete in AjaxExamples will demonstrate the issue if the page has been scrolled BEFORE entering any text.
This is caused by a problem in the way AjaxAutocomplete nests its container tags, but the problem didn't manifest itself in earlier versions of prototype. I have created a pull request #906

**Comment by darkv** [comment]
Resolved by #906.
