### ISSUE TITLE
WONDER-675 ERMDDatePicker should support localized formatters

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#93]
Reported by Marius Soutier

Currently it relies on the this rule:

smartAttribute.className = 'com.webobjects.foundation.NSTimestamp' => formatter : "%Y-%m-%d"
from ERModernDirectToWeb

**Comment by fbarthez** [comment]
To get localized formatters, simply define one or more date patterns in your Localizable.strings files, e.g.:

"defaultDateFormat" = "%d.%m.%Y";

And reference them from rules like this:

60 : *true* => defaultDateFormat = "D2W.defaultDateFormat" [er.directtoweb.ERDDelayedLocalizedAssignment]
60 : smartAttribute.prototypeName = 'dateTime' => formatter = "defaultDateFormat" [ERDDelayedKeyValueAssignment]

The first one will set "defaultDateFormat" to the localized pattern and the second one will apply it as the default for any attribute with a prototype named "dateTime". The key "defaultDateFormat" is entirely arbitrary…

**Comment by darkv** [comment]
Perhaps that explanation should be put into Javadocs?
