### ISSUE TITLE
WONDER-674 ERXRequest.isRequestSecure is broken for servlet deployment 

### ISSUE THREAD

**Issue by pascalrobert** [wocommunity/wonder#94]
Reported by René Bock

I just noticed, that in servlet deployment the method ERXRequest.isRequestSecure doesn't return the expected value for https requests.

The reason is, that if the request header "https" is not set, there is check for header "x-webobjects-server-port"

but in servlet mode the header "x-webobjects-servlet-server-port" is sent...

By the way, the same is true for the header "x-webobjects-server-name" vs. "x-webobjects-servlet-server-name"

As consquence, generateCompleteUrls will generate the wrong protocol part.

**Comment by darkv** [comment]
@renebock is this still an issue?

**Comment by renebock** [comment]
Yes it is still a potential issue.  I will try to provide a patch....

**Comment by paulhoadley** [comment]
Is anyone still interested in this?

**Comment by paulhoadley** [comment]
@renebock, did you end up taking a look? Is it still an issue that interests you?

**Comment by renebock** [comment]
@paulhoadley This issue has been fixes with commit 8fe12637fc610b57b86b4af61cb7f09dea3570be and this ticket may be closed.

It seems, that I had forgotten to mention this ticket in the pull request corresponding to the commit.

**Comment by paulhoadley** [comment]
Thanks @renebock!
