### ISSUE TITLE
Get Wonder building on Java 16

### ISSUE THREAD

**Issue by hugith** [wocommunity/wonder#943]
Exactly what it says on the label. Not intended to actually make Wonder Java 16 compatible, just allow more recent compilers to compile it with the 1.8 source/target versions.

**Comment by hugith** [comment]
Couple of things still to do:

- ERProfiling/WeavingClassLoader.java uses classes `Resource` and `URLClassPath` from `sun.misc`. These classes are available from `jdk.internal` in more recent releases. Question is: Do we want to bother or do we just move ERProfiling to "Archive"/delete it?
- ERXiss/ERXML.java has a public static variable called versionDate which uses NSTimeZone which uses internal APIs. Tests fail because of this. We _could_ create a separate maven profile to run thost tests with `--illegal-access=permit`. But do we need to? Does anyone use ERXiss or can we move that to "Archive"/delete it?

**Comment by paulhoadley** [comment]
> Do we want to bother or do we just move ERProfiling to "Archive"/delete it?

As discussed elsewhere, I still use ERProfiling, so I'd vote for _bother_ if it's doable.

> Does anyone use ERXiss or can we move that to "Archive"/delete it?

My vote is for _delete._

**Comment by paulhoadley** [comment]
Hey @hugith, where are we on this?

**Comment by hugith** [comment]
I don't use ERPRofiling so I haven't looked into it. I opted to create my own fork instead.

**Comment by paulhoadley** [comment]
Oh right, sorry—I didn't review the whole conversation above. Should we close this ticket then?

**Comment by hugith** [comment]
You don’t have to keep it open on my account. Depends on if you want Wonder building on newer JDKs I guess.

**Comment by paulhoadley** [comment]
We seem to have several tickets on the go that are variations on a theme. In #944 we're talking about Java 11 for `8.0-SNAPSHOT`, but I've also suggested we skip 11 and head straight to 17. Let's close this here and continue in #944.
