### ISSUE TITLE
Wonder-663 ERMODWizardPage doesn't display errors thrown by validationKeys when the nextAction is called

### ISSUE THREAD

**Issue by nullterminated** [wocommunity/wonder#97]
Using a rule like 

pageConfiguration = 'Foo' && tabKey = 'Bar' => validationKeys = "(validateXY)"

with a ERMODWizard page does not display an error on the Bar tab if validateXY throws a validation exception.

**Comment by fbarthez** [comment]
I still think the issue can be closed. Just subclass Ramsey's default implementation of the [validation delegate](https://github.com/wocommunity/wonder/commit/3ecb423dd6b575451f85b5f0ced77d655411d84f#diff-a5277a6824863a8fba5fcdca9e3bb96eR556) and specify your custom delegate via the rules, using "validationDelegateClassName" as the key.

**Comment by paulhoadley** [comment]
Let's close this. If it turns up again for someone, we can re-visit.
