### ISSUE TITLE
ERXStaticResourceRequestHandler wodata ignored in enviroment with customized WOAdaptorURL

### ISSUE THREAD

**Issue by xplants** [wocommunity/wonder#999]
When a static resources, from a jar, is accessed in an environment with a custom adaptorUrl that do not start with "/cgi-bin" the wodata parameter from request is ignored and the resource is not served.

### A possibile solution 
In ERXStaticResourceRequestHandler.java  the `handleRequest` method the `uri` variable should be evaluated against `application.cgiAdaptorURL()` instead of the static string `/cgi-bin`

**Comment by sal-bock** [comment]
I wonder why the first part of the  `uri` should be evaluated at all.  It should be sufficient to check, that wodata is provided as GET parameter.

But if the check is necessary, then the `uri` variable should be evaluated against `request.applicationURLPrefix()`.
In fact, this method is used in `WOResourceManager. urlForResourceNamed` to generate the url.  The static  resources will be loaded from the jar, even if there is a proxy server is part of the game.

**Comment by paulhoadley** [comment]
PR merged—thanks.
